# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zishengy/Projects/GMLS_Solver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zishengy/Projects/GMLS_Solver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zishengy/Projects/GMLS_Solver/CMakeFiles /home/zishengy/Projects/GMLS_Solver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zishengy/Projects/GMLS_Solver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nsmpi

# Build rule for target.
nsmpi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nsmpi
.PHONY : nsmpi

# fast build rule for target.
nsmpi/fast:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/build
.PHONY : nsmpi/fast

main/ns.o: main/ns.cpp.o

.PHONY : main/ns.o

# target to build an object file
main/ns.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/main/ns.cpp.o
.PHONY : main/ns.cpp.o

main/ns.i: main/ns.cpp.i

.PHONY : main/ns.i

# target to preprocess a source file
main/ns.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/main/ns.cpp.i
.PHONY : main/ns.cpp.i

main/ns.s: main/ns.cpp.s

.PHONY : main/ns.s

# target to generate assembly for a file
main/ns.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/main/ns.cpp.s
.PHONY : main/ns.cpp.s

src/GMLS_solver.o: src/GMLS_solver.cpp.o

.PHONY : src/GMLS_solver.o

# target to build an object file
src/GMLS_solver.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/GMLS_solver.cpp.o
.PHONY : src/GMLS_solver.cpp.o

src/GMLS_solver.i: src/GMLS_solver.cpp.i

.PHONY : src/GMLS_solver.i

# target to preprocess a source file
src/GMLS_solver.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/GMLS_solver.cpp.i
.PHONY : src/GMLS_solver.cpp.i

src/GMLS_solver.s: src/GMLS_solver.cpp.s

.PHONY : src/GMLS_solver.s

# target to generate assembly for a file
src/GMLS_solver.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/GMLS_solver.cpp.s
.PHONY : src/GMLS_solver.cpp.s

src/boundary_condition.o: src/boundary_condition.cpp.o

.PHONY : src/boundary_condition.o

# target to build an object file
src/boundary_condition.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/boundary_condition.cpp.o
.PHONY : src/boundary_condition.cpp.o

src/boundary_condition.i: src/boundary_condition.cpp.i

.PHONY : src/boundary_condition.i

# target to preprocess a source file
src/boundary_condition.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/boundary_condition.cpp.i
.PHONY : src/boundary_condition.cpp.i

src/boundary_condition.s: src/boundary_condition.cpp.s

.PHONY : src/boundary_condition.s

# target to generate assembly for a file
src/boundary_condition.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/boundary_condition.cpp.s
.PHONY : src/boundary_condition.cpp.s

src/make_geometry.o: src/make_geometry.cpp.o

.PHONY : src/make_geometry.o

# target to build an object file
src/make_geometry.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/make_geometry.cpp.o
.PHONY : src/make_geometry.cpp.o

src/make_geometry.i: src/make_geometry.cpp.i

.PHONY : src/make_geometry.i

# target to preprocess a source file
src/make_geometry.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/make_geometry.cpp.i
.PHONY : src/make_geometry.cpp.i

src/make_geometry.s: src/make_geometry.cpp.s

.PHONY : src/make_geometry.s

# target to generate assembly for a file
src/make_geometry.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/make_geometry.cpp.s
.PHONY : src/make_geometry.cpp.s

src/make_geometry_manifold.o: src/make_geometry_manifold.cpp.o

.PHONY : src/make_geometry_manifold.o

# target to build an object file
src/make_geometry_manifold.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/make_geometry_manifold.cpp.o
.PHONY : src/make_geometry_manifold.cpp.o

src/make_geometry_manifold.i: src/make_geometry_manifold.cpp.i

.PHONY : src/make_geometry_manifold.i

# target to preprocess a source file
src/make_geometry_manifold.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/make_geometry_manifold.cpp.i
.PHONY : src/make_geometry_manifold.cpp.i

src/make_geometry_manifold.s: src/make_geometry_manifold.cpp.s

.PHONY : src/make_geometry_manifold.s

# target to generate assembly for a file
src/make_geometry_manifold.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/make_geometry_manifold.cpp.s
.PHONY : src/make_geometry_manifold.cpp.s

src/neighbor_list.o: src/neighbor_list.cpp.o

.PHONY : src/neighbor_list.o

# target to build an object file
src/neighbor_list.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/neighbor_list.cpp.o
.PHONY : src/neighbor_list.cpp.o

src/neighbor_list.i: src/neighbor_list.cpp.i

.PHONY : src/neighbor_list.i

# target to preprocess a source file
src/neighbor_list.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/neighbor_list.cpp.i
.PHONY : src/neighbor_list.cpp.i

src/neighbor_list.s: src/neighbor_list.cpp.s

.PHONY : src/neighbor_list.s

# target to generate assembly for a file
src/neighbor_list.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/neighbor_list.cpp.s
.PHONY : src/neighbor_list.cpp.s

src/neighbor_list_manifold.o: src/neighbor_list_manifold.cpp.o

.PHONY : src/neighbor_list_manifold.o

# target to build an object file
src/neighbor_list_manifold.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/neighbor_list_manifold.cpp.o
.PHONY : src/neighbor_list_manifold.cpp.o

src/neighbor_list_manifold.i: src/neighbor_list_manifold.cpp.i

.PHONY : src/neighbor_list_manifold.i

# target to preprocess a source file
src/neighbor_list_manifold.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/neighbor_list_manifold.cpp.i
.PHONY : src/neighbor_list_manifold.cpp.i

src/neighbor_list_manifold.s: src/neighbor_list_manifold.cpp.s

.PHONY : src/neighbor_list_manifold.s

# target to generate assembly for a file
src/neighbor_list_manifold.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/neighbor_list_manifold.cpp.s
.PHONY : src/neighbor_list_manifold.cpp.s

src/poisson.o: src/poisson.cpp.o

.PHONY : src/poisson.o

# target to build an object file
src/poisson.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/poisson.cpp.o
.PHONY : src/poisson.cpp.o

src/poisson.i: src/poisson.cpp.i

.PHONY : src/poisson.i

# target to preprocess a source file
src/poisson.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/poisson.cpp.i
.PHONY : src/poisson.cpp.i

src/poisson.s: src/poisson.cpp.s

.PHONY : src/poisson.s

# target to generate assembly for a file
src/poisson.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/poisson.cpp.s
.PHONY : src/poisson.cpp.s

src/poisson_manifold.o: src/poisson_manifold.cpp.o

.PHONY : src/poisson_manifold.o

# target to build an object file
src/poisson_manifold.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/poisson_manifold.cpp.o
.PHONY : src/poisson_manifold.cpp.o

src/poisson_manifold.i: src/poisson_manifold.cpp.i

.PHONY : src/poisson_manifold.i

# target to preprocess a source file
src/poisson_manifold.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/poisson_manifold.cpp.i
.PHONY : src/poisson_manifold.cpp.i

src/poisson_manifold.s: src/poisson_manifold.cpp.s

.PHONY : src/poisson_manifold.s

# target to generate assembly for a file
src/poisson_manifold.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/poisson_manifold.cpp.s
.PHONY : src/poisson_manifold.cpp.s

src/sparse_matrix.o: src/sparse_matrix.cpp.o

.PHONY : src/sparse_matrix.o

# target to build an object file
src/sparse_matrix.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/sparse_matrix.cpp.o
.PHONY : src/sparse_matrix.cpp.o

src/sparse_matrix.i: src/sparse_matrix.cpp.i

.PHONY : src/sparse_matrix.i

# target to preprocess a source file
src/sparse_matrix.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/sparse_matrix.cpp.i
.PHONY : src/sparse_matrix.cpp.i

src/sparse_matrix.s: src/sparse_matrix.cpp.s

.PHONY : src/sparse_matrix.s

# target to generate assembly for a file
src/sparse_matrix.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/sparse_matrix.cpp.s
.PHONY : src/sparse_matrix.cpp.s

src/stokes.o: src/stokes.cpp.o

.PHONY : src/stokes.o

# target to build an object file
src/stokes.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/stokes.cpp.o
.PHONY : src/stokes.cpp.o

src/stokes.i: src/stokes.cpp.i

.PHONY : src/stokes.i

# target to preprocess a source file
src/stokes.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/stokes.cpp.i
.PHONY : src/stokes.cpp.i

src/stokes.s: src/stokes.cpp.s

.PHONY : src/stokes.s

# target to generate assembly for a file
src/stokes.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/stokes.cpp.s
.PHONY : src/stokes.cpp.s

src/time_integration.o: src/time_integration.cpp.o

.PHONY : src/time_integration.o

# target to build an object file
src/time_integration.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/time_integration.cpp.o
.PHONY : src/time_integration.cpp.o

src/time_integration.i: src/time_integration.cpp.i

.PHONY : src/time_integration.i

# target to preprocess a source file
src/time_integration.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/time_integration.cpp.i
.PHONY : src/time_integration.cpp.i

src/time_integration.s: src/time_integration.cpp.s

.PHONY : src/time_integration.s

# target to generate assembly for a file
src/time_integration.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/time_integration.cpp.s
.PHONY : src/time_integration.cpp.s

src/write_data.o: src/write_data.cpp.o

.PHONY : src/write_data.o

# target to build an object file
src/write_data.cpp.o:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/write_data.cpp.o
.PHONY : src/write_data.cpp.o

src/write_data.i: src/write_data.cpp.i

.PHONY : src/write_data.i

# target to preprocess a source file
src/write_data.cpp.i:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/write_data.cpp.i
.PHONY : src/write_data.cpp.i

src/write_data.s: src/write_data.cpp.s

.PHONY : src/write_data.s

# target to generate assembly for a file
src/write_data.cpp.s:
	$(MAKE) -f CMakeFiles/nsmpi.dir/build.make CMakeFiles/nsmpi.dir/src/write_data.cpp.s
.PHONY : src/write_data.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... nsmpi"
	@echo "... main/ns.o"
	@echo "... main/ns.i"
	@echo "... main/ns.s"
	@echo "... src/GMLS_solver.o"
	@echo "... src/GMLS_solver.i"
	@echo "... src/GMLS_solver.s"
	@echo "... src/boundary_condition.o"
	@echo "... src/boundary_condition.i"
	@echo "... src/boundary_condition.s"
	@echo "... src/make_geometry.o"
	@echo "... src/make_geometry.i"
	@echo "... src/make_geometry.s"
	@echo "... src/make_geometry_manifold.o"
	@echo "... src/make_geometry_manifold.i"
	@echo "... src/make_geometry_manifold.s"
	@echo "... src/neighbor_list.o"
	@echo "... src/neighbor_list.i"
	@echo "... src/neighbor_list.s"
	@echo "... src/neighbor_list_manifold.o"
	@echo "... src/neighbor_list_manifold.i"
	@echo "... src/neighbor_list_manifold.s"
	@echo "... src/poisson.o"
	@echo "... src/poisson.i"
	@echo "... src/poisson.s"
	@echo "... src/poisson_manifold.o"
	@echo "... src/poisson_manifold.i"
	@echo "... src/poisson_manifold.s"
	@echo "... src/sparse_matrix.o"
	@echo "... src/sparse_matrix.i"
	@echo "... src/sparse_matrix.s"
	@echo "... src/stokes.o"
	@echo "... src/stokes.i"
	@echo "... src/stokes.s"
	@echo "... src/time_integration.o"
	@echo "... src/time_integration.i"
	@echo "... src/time_integration.s"
	@echo "... src/write_data.o"
	@echo "... src/write_data.i"
	@echo "... src/write_data.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

